name: payment_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  get_it: ^7.6.0
  webview_flutter: ^4.2.0
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita_Regular.otf
        - asset: assets/fonts/Gordita_Medium.otf
          weight: 500
        - asset: assets/fonts/Gordita_Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita_Light.otf
          weight: 300
